---
version: '3.5'
services:
  postgres:
    image: debezium/postgres:10.0
    hostname: postgres
    container_name: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    volumes:
    - $PWD/docker/postgres/initdb.sql:/docker-entrypoint-initdb.d/z99_dump.sql

networks:
  default:
    name: kappa_network
